app/base/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name="home"),
    path('signup', views.signup, name="signup"),
    path('login', views.login_view, name="login"),
    path('main_user_dashboard', views.main_user_dashboard, name="main_user_dashboard"),
    path('signout', views.signout, name="signout")
]

app/base/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'authentication.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('workers/', include(('workers.urls', 'workers'), namespace='workers')),
    path('hoteladmin/', include(('hoteladmin.urls', 'hoteladmin'), namespace='hoteladmin')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication'))
]

app/base/hoteladmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('empleado/', views.empleado, name='empleado'),
    path('nuevohotel/', views.nuevo_hotel, name='nuevohotel'),
    path('nuevahabitacion/', views.nueva_habitacion, name='nuevahabitacion'),
    path('empleados/', views.buscar_empleado, name='empleados'),
    path('ver_empleado/', views.eliminar_empleado, name='ver_empleado'),
    path('hoteles/', views.buscar_hotel, name='hoteles'),
    path('ver_hotel/', views.eliminar_hotel, name='ver_hotel'),
    path('habitaciones/', views.eliminar_habitacion, name='habitaciones')
]

app/base/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('signup', views.signup, name="signup"),
    path('login', views.login, name="login"),
    path('results', views.hotel_search, name="results"),
    path('rooms', views.available_rooms, name="rooms"),
    path('new_bookings', views.book, name="new_bookings"),
    path('bookings', views.bookings, name="bookings"),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('invoice', views.invoice, name="invoice"),
    path('account', views.info_cuenta, name='account'),
    path('delete_account/<username>/', views.eliminar_cuenta, name='delete'),
]

app/base/workers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.generador, name='workers'),
    path('vencimiento', views.vencimiento, name='vencimiento'),
    path('new_invoice', views.generar_factura, name='new_invoice')
]

app/base/users/forms.py
from django import forms
from authentication.models import Cliente, Cuenta
from django.contrib.auth.hashers import make_password


class ClienteForm(forms.ModelForm):
    """
    Formulario para crear y actualizar instancias de clientes.

    Este formulario incluye los siguientes campos:
    - nombre
    - apellido_paterno
    - apellido_materno
    - telefono
    - fecha_de_nacimiento

    Widgets:
    - fecha_de_nacimiento: Un widget de input fecha con 'tipo' establecido en 'fecha'.
    """

    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido_paterno', 'apellido_materno', 'telefono', 'fecha_de_nacimiento']
        widgets = {
            'fecha_de_nacimiento': forms.DateInput(attrs={'type': 'date'}),
        }


class CuentaForm(forms.ModelForm):
    """
    Formulario para crear y actualizar instancias de cuentas.

    Este formulario incluye los siguientes campos:
    - correo_electronico
    - contrasena

    Widgets:
    - contrasena: Un widget PasswordInput para ocultar la entrada de la contraseña.

    Methods:
    - save: Sobreescribe el método de guardado predeterminado para hashear
    la contraseña antes de guardarla.
    """
    class Meta:
        model = Cuenta
        fields = ['correo_electronico', 'contrasena']
        widgets = {
            'contrasena': forms.PasswordInput()
        }
    
    def save(self, commit=True):
        """
        Guarda una instancia de cuenta con una contraseña hasheada.
        Sobreescribe el método de guardado predeterminado para codificar 
        la contraseña antes de guardarla en la base de datos.
        
        Args:
            commit (bool): Si es verdad, guarda la instancia a la BD. 
            De manera predeterminada es verdad.

        Returns:
            Cuenta: La instancia de cuenta guardada.
        """
        cuenta = super().save(commit=False)
        cuenta.contrasena = make_password(self.cleaned_data['contrasena'])
        if commit:
            cuenta.save()
        return cuenta

app/base/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from users.models import Hotel, Habitacion, Reservacion
from workers.models import Generar, Factura
from authentication.models import Cliente, Cuenta, Poseer
from django.contrib.auth.models import User
from django.contrib import auth
import authentication.views as auth
from datetime import datetime
from django.db.models import Max
from django.http import JsonResponse
import requests
from django.db.models import Q
from django.utils import timezone
from django.db.models import FloatField, F, Func
from django.db.models.functions import ACos, Cos, Radians, Sin
from django.db.models import Count
from django.contrib import messages
from .forms import ClienteForm, CuentaForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.hashers import check_password
from django.db.models.functions import ExtractDay
import pytz

def homepage(request):
    """
    Redirección a la página principal.

    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    return render(request, 'users/index.html')


def signup(request):
    """
    Método que registra un nuevo usuario. Llama al método signup de authentication.

    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    return auth.signup(request)


def login(request):
    """
    Método que da acceso a un usuario. Llama al método login_view de authentication.

    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    return auth.login_view(request)


def get_coordenadas(direccion):
    """
    Obtiene las coordenadas geográficas de una dirección real.

    Args:
        direccion (string): Dirección física.
 
    Returns:
        (float,float): Tupla con la latitud y longitud.
    """
    API_KEY = '' # IMPORTANTE: Ingresar una API_KEY de Google Maps válida para que funcione la búsqueda por distancia.
    
    params = {
        'key': API_KEY,
        'address': direccion
    }
    
    base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
    response = requests.get(base_url, params=params).json()
    
    response.keys()
    
    if response['status'] == 'OK':
        geometry = response['results'][0]['geometry']
        lat = geometry['location']['lat']
        lon = geometry['location']['lng']
        return (lat,lon)
    else:
        print("Error en la respuesta de la API")
        return (0,0)


class Radians(Func):
    """
    Representa la función RADIANS de SQL que convierte grados a radianes.

    Attributes:
        function: Ajustado a RADIANS indicando la función SQL a usar.
        output_field: Especifica que el valor de salida es flotante.
    """
    function = 'RADIANS'
    output_field = FloatField()

class Sin(Func):
    """
    Representa la función SQL SIN para calcular el seno de un ángulo.
    
    Attributes:
        function: Ajustado a SIN.
        output_field: Especifica que el valor de salida es flotante.
    """
    function = 'SIN'
    output_field = FloatField()

class Cos(Func):
    """
    Representa la función SQL COS para calcular el coseno de un ángulo.
    
    Attributes:
        function: Ajustado a COS.
        output_field: Especifica que el valor de salida es flotante.
    """
    function = 'COS'
    output_field = FloatField()

class Acos(Func):
    """
    Representa la función SQL ACOS para calcular el arco coseno de un ángulo.
    
    Attributes:
        function: Ajustado a ACOS.
        output_field: Especifica que el valor de salida es flotante.
    """
    function = 'ACOS'
    output_field = FloatField()
    
def calculate_distance(lat1, lon1, lat2, lon2):
    """
    Esta función calcula la distancia del círculo máximo entre dos puntos
    de la Tierra utilizando sus coordenadas de latitud y longitud. 
    El cálculo se basa en la fórmula de Haversine.
        
    Args:
        lat1 (float): Latitud del primer punto en grados.
        lon1 (float): Longitud del primer punto en grados.
        lat2 (float): Latitud del segundo punto en grados.
        lon2 (float): Longitud del segundo punto en grados.
    Returns:
        distance (float): La distancia entre los dos puntos en kilómetros.
    """
    R = 6371  # Radio de la Tierra en kilómetros
    dlat = Radians(lat2 - lat1)
    dlon = Radians(lon2 - lon1)
    a = Sin(dlat / 2) ** 2 + Cos(Radians(lat1)) * Cos(Radians(lat2)) * Sin(dlon / 2) ** 2
    c = 2 * ACos(Cos(a))
    distance = R * c
    return distance


def find_nearest_hotels(latitude, longitude):
    """
    Encuentra los hoteles más cercanos según la latitud y
    longitud recibidas y la lista de hoteles guardados
    en la base de datos con sus coordenadas respectivas.
    Para ello, se calcula la distancia en kilómetros usando
    un QuerySet y se ordena de menor a mayor.
        
    Args:
        latitude (float): Latitud del punto en grados.
        lonngitude (float): Longitud del punto en grados.
    Returns:
        hotels (QuerySet): Listado de hoteles ordenados por distancia.
    """
    hotels = Hotel.objects.annotate(
        distance=calculate_distance(
            latitude,
            longitude,
            F('latitud'),
            F('longitud')
        )
    ).order_by('distance')
    
    return hotels
    

def get_available_rooms(hotel_id, checkin_date, checkout_date):
    """
    Dado un hotel y fechas particulares de checkin y checkout,
    ecnuentra las habitaciones del hotel disponibles que no
    tienen reservaciones dentro de ese lapso de fechas.
        
    Args:
        hotel_id (int): Identificador del hotel.
        checkin_date (datetime): Día y hora del checkin.
        checkout_date (datetime): Día y hora del checkout.
    Returns:
        habitaciones (QuerySet): Listado de habitaciones disponibles.
    """
    reservaciones = Reservacion.objects.filter(
        Q(check_in__lte=checkin_date, check_out__gte=checkin_date) |
        Q(check_in__lte=checkout_date, check_out__gte=checkout_date) |
        Q(check_in__gte=checkin_date, check_out__lte=checkout_date),
        id_hotel=hotel_id
    )
        
    habitaciones_ocupadas = reservaciones.values_list('id_habitacion', flat=True)
        
    habitaciones = Habitacion.objects.filter(
        id_hotel=hotel_id
    ).exclude(
        id_habitacion__in=habitaciones_ocupadas
    )
    
    return habitaciones


def hotel_search(request):
    """
    Página de búsqueda de hoteles. Dado una dirección física como
    destino y fechas de checkin y checkout, redirige a una página
    con los hoteles que tienen habitaciones que cumplen esas condiciones.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == 'POST':
        destino = request.POST.get('destino')

        if destino is None or destino == '':
            messages.error(request, "Por favor ingrese un destino")
            return redirect('users:homepage')
        
        checkin_date = request.POST.get('checkin_date')
        checkout_date = request.POST.get('checkout_date')

        if checkin_date is None or checkin_date == '':
            messages.error(request, "Por favor ingrese una fecha de check-in")
            return redirect('users:homepage')

        if checkout_date is None or checkout_date == '':
            messages.error(request, "Por favor ingrese una fecha de check-out")
            return redirect('users:homepage')
    
        if checkin_date >= checkout_date:
            messages.error(request, "La fecha de check-out no puede ser anterior o igual a la fecha de check-in")
            return redirect('users:homepage')

        checkin_date = datetime.strptime(checkin_date, '%m/%d/%Y %I:%M %p')
        checkout_date = datetime.strptime(checkout_date, '%m/%d/%Y %I:%M %p')

        local_timezone = pytz.timezone('Mexico/General')

        checkin_date = local_timezone.localize(checkin_date)
        checkout_date = local_timezone.localize(checkout_date)

        today = timezone.now().astimezone(local_timezone)

        if checkin_date <= today:
            messages.error(request, "La fecha de check-in no puede ser anterior o igual a la fecha actual")
            return redirect('users:homepage')
        
        request.session['checkin_date'] = checkin_date.isoformat()
        request.session['checkout_date'] = checkout_date.isoformat()

        (latitude, longitude) = get_coordenadas(destino)
        hoteles_cercanos = find_nearest_hotels(latitude, longitude)

        hoteles_con_habitaciones = []
        for hotel in hoteles_cercanos:
            habitaciones_disponibles = get_available_rooms(hotel.id_hotel, checkin_date, checkout_date)
            if habitaciones_disponibles.exists():
                hoteles_con_habitaciones.append(hotel)
        
        return render(request, 'users/hotel_search.html', {'hoteles': hoteles_con_habitaciones})
    else:
        return render(request, 'index.html')


def available_rooms(request):
    """
    Página de búsqueda de habitaciones. Dado una dirección física como
    destino y fechas de checkin y checkout, muestra las habitaciones
    disponibles de un hotel que cumplen esas condiciones.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:

app/base/users/templates/users/account.html
{% extends "users/base.html" %}

{% load static %}

{% load custom_filters %}

{% block content %}  

<style>
    .data-container {
        width: 80%;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        margin-top: 40px;
    }
    h1, h2 {
        color: #333;
    }
    form {
        margin-bottom: 20px;
    }
    form h2 {
        border-bottom: 2px solid #ddd;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }
    form .field {
        margin-bottom: 15px;
    }
    form label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }
    form input[type="text"],
    form input[type="email"],
    form input[type="password"],
    form input[type="date"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 4px;
    }
    form button {
        background-color: #007bff;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    form button:hover {
        background-color: #0056b3;
    }
    .info {
        list-style-type: none;
        padding: 0;
    }
    .info li {
        background-color: #f9f9f9;
        margin: 5px 0;
        padding: 10px;
        border-radius: 4px;
    }
</style>

<section class="site-hero inner-page overlay" style="background-image: url({% static 'images/bookingPage.png' %})" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row site-hero-inner justify-content-center align-items-center">
          <div class="col-md-10 text-center" data-aos="fade">
              <h2 class="text-white d-block  mb-3">Visualiza y Administra tu</h2>
              <h1 class="heading">Cuenta de Usuario</h1>
          </div>
      </div>
    </div>


    <section class="section contact-section" id="next">
      <div class="container">
        <div class="row">
          <div class="col-md-7" data-aos="fade-up" data-aos-delay="100">
            
            <form method="post" class="bg-white p-md-5 p-4 mb-5 border">
                {% csrf_token %}
            
                <div class="row">
                <div class="col-md-12 form-group">
                    {{ cliente_form.nombre.label_tag }} {{ cliente_form.nombre }}
                </div>
                </div>

                <div class="row">
                <div class="col-md-6 form-group">
                    {{ cliente_form.apellido_paterno.label_tag }} {{ cliente_form.apellido_paterno }}
                </div>
                <div class="col-md-6 form-group">
                    {{ cliente_form.apellido_materno.label_tag }} {{ cliente_form.apellido_materno }}
                </div>
              </div>
                
              <div class="row">
                <div class="col-md-6 form-group">
                    {{ cliente_form.telefono.label_tag }} {{ cliente_form.telefono }}
                </div>
                <div class="col-md-6 form-group">
                    {{ cliente_form.fecha_de_nacimiento.label_tag }} {{ cliente_form.fecha_de_nacimiento }}
                </div>
              </div>

                <div class="row mb-4">
                <div class="col-md-6 form-group text-black font-weight-bold">
                    {{ cuenta_form.correo_electronico.label_tag }} {{ cuenta_form.correo_electronico }}
                </div>
                <div class="col-md-6 form-group text-black font-weight-bold">
                    {{ cuenta_form.contrasena.label_tag }} {{ cuenta_form.contrasena }}
                </div>
              </div>

                <div class="row">
                <div class="col form-group">
                    <input type="submit" value="Guardar cambios" class="btn btn-primary text-white py-2 mr-3 font-weight-bold">
                    <span class="mr-3 font-family-serif"><em>o</em></span> 
                    <a href="{% url 'users:delete' username=request.user.username %}" class="text-uppercase letter-spacing-1 text-danger">Eliminar cuenta</a>
                </div>
              </div>
            </form>
          </div>

          <div class="col-md-5" data-aos="fade-up" data-aos-delay="200">
            <div class="row">
              <div class="col-md-10 ml-auto contact-info">
                  <p><span class="d-block">Nombre:</span> <span class="text-black"> {{cliente.nombre}} </span></p>
                  <p><span class="d-block">Apellido paterno:</span> <span class="text-black"> {{cliente.apellido_paterno}} </span></p>
                  <p><span class="d-block">Apellido materno:</span> <span class="text-black"> {{cliente.apellido_materno}}</span></p>
                  <p><span class="d-block">Teléfono:</span> <span class="text-black"> {{cliente.telefono}}</span></p>
                  <p><span class="d-block">Fecha de nacimiento:</span> <span class="text-black"> {{cliente.fecha_de_nacimiento}}</span></p>
                  <p><span class="d-block">Correo electrónico:</span> <span class="text-black"> {{cuenta.correo_electronico}}</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

app/base/users/templates/users/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hoteles Estrella</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <script src="{% static 'js/moment.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}">
    <script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/notyf.min.css' %}">
  </head>
  <body>
    <header class="site-header js-site-header">
      <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-6 col-lg-4 site-logo" data-aos="fade"><a href="{% url 'users:homepage' %}">HOTELES ESTRELLA</a></div>
            <div class="col-6 col-lg-8">

            <div class="site-menu-toggle js-site-menu-toggle"  data-aos="fade">
              <span></span>
              <span></span>
              <span></span>
            </div>
        
        <div class="site-navbar js-site-navbar">
            {% if perms.workers.puede_generar %} 
            <nav role="navigation">
                <div class="container">
                  <div class="row full-height align-items-center">
                    <div class="col-md-6 mx-auto">
                      <ul class="list-unstyled menu">
                        <li class="active"><a href="{% url 'workers:workers' %}">Cuentas de gastos</a></li>
                        <li><a href="{% url 'authentication:signout' %}">Cerrar Sesión</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </nav>
            {% endif %}

            {% if perms.users.puede_administrar %} 
            <nav role="navigation">
                <div class="container">
                  <div class="row full-height align-items-center">
                    <div class="col-md-6 mx-auto">
                      <ul class="list-unstyled menu">
                        <li class="active"><a href="{% url 'hoteladmin:home' %}">Panel de Administración</a></li>
                        <li><a href="{% url 'authentication:signout' %}">Cerrar Sesión</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </nav>
            {% endif %}

            {% if user.is_authenticated %} 
            <nav role="navigation">
                <div class="container">
                  <div class="row full-height align-items-center">
                    <div class="col-md-6 mx-auto">
                      <ul class="list-unstyled menu">
                        <li class="active"><a href="{% url 'users:account' %}">Cuenta</a></li>
                        <li class="active"><a href="{% url 'users:bookings' %}">Reservaciones</a></li>
                        <li><a href="{% url 'authentication:signout' %}">Cerrar Sesión</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </nav>
            {% else %}
            <nav role="navigation">
                <div class="container">
                  <div class="row full-height align-items-center">
                    <div class="col-md-6 mx-auto">
                      <ul class="list-unstyled menu">
                        <li class="active"><a href="{% url 'authentication:login' %}">Iniciar Sesión</a></li>
                        <li><a href="{% url 'authentication:signup' %}">Registrarse</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </nav>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- END head -->

    {% block content %}
    {% endblock %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var notyf = new Notyf({
                duration: 5000,  // Duración en milisegundos
                dismissible: true,
                ripple: true,
                position: {
                    x: 'center',
                    y: 'top',
                },
                types: [
                  {
                    type: 'success',
                    background: 'orange',
                  },
                  {
                    type: 'error',
                    background: 'indianred',
                  }
                ]
            });

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        notyf.success("{{ message }}");
                    {% elif message.tags == 'error' %}
                        notyf.error("{{ message }}");
                    {% else %}
                        notyf.open({
                            type: '{{ message.tags }}',
                            message: "{{ message }}"
                        });
                    {% endif %}
                {% endfor %}
            {% endif %}
        });
    </script>
    <script src="{% static 'js/notyf.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script> 
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script> 
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

app/base/users/templates/users/delete_account.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}  

<section class="site-hero inner-page overlay" style="background-image: url({% static 'images/bookingPage.png' %})" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row site-hero-inner justify-content-center align-items-center">
          <div class="col-md-10 text-center" data-aos="fade">
              <h2 class="text-white d-block  mb-3">Ten cuidado, ya que puedes</h2>
              <h1 class="heading">Eliminar tu Cuenta</h1>
          </div>
      </div>
    </div>

    <section class="section bg-light">

      <div class="container">
      
        <div class="site-block-half d-block d-lg-flex bg-white" data-aos="fade" data-aos-delay="100">
          <a href="#" class="image d-block bg-image-2" style="background-image: url({% static 'images/delete_accountPage.png' %});"></a>
          <div class="text">
            <h2 class="mb-4">¿Estás seguro de que quieres eliminar tu cuenta?</h2>
            <p>Eliminar tu cuenta es una acción permanente y no se puede deshacer. Perderás acceso a todas tus reservaciones y cualquier otra información asociada con tu cuenta.</p>
            
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary text-white py-2 mr-3 font-weight-bold" >Sí, Eliminar</button> 
                <span class="mr-3 font-family-serif"><em>o</em></span> 
                <a href="{% url 'users:account' %}" class="text-uppercase letter-spacing-1" >Cancelar</a>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

app/base/users/templates/users/index.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

    <section class="site-hero overlay" style="background-image: url({% static 'images/landingPage.jpg' %})" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
          <div class="col-md-10 text-center" data-aos="fade-up">
            <h2 class="text-white d-block  mb-3">Disfruta de una experiencia</h2>
            <h1 class="heading">SIN IGUAL</h1>
          </div>
        </div>
      </div>

    </section>
    <!-- END section -->

    <section class="section bg-light pb-0"  >
      <div class="container">
       
        <div class="row check-availabilty">
          <div class="block-32" data-aos="fade-up" data-aos-offset="-200">
              <form method="POST" action="{% url 'users:results' %}">
                {% csrf_token %}
    <div class="row">
        <div class="col">
            <label for="destino" class="font-weight-bold text-black">Destino</label>
            <div class="field-icon-wrap">
                <input type="text" name="destino" class="form-control text-black">
            </div>
        </div>              
        <div class="col">
            <label for="checkin_date" class="font-weight-bold text-black">Check-In</label>               
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    <input type="text" name="checkin_date" class="form-control datetimepicker-input text-black" data-target="#datetimepicker1"/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
                </div>
        </div>
        <div class="col">
            <label for="checkout_date" class="font-weight-bold text-black">Check-Out</label>
                <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                    <input type="text" name="checkout_date" class="form-control datetimepicker-input text-black" data-target="#datetimepicker2"/>
                <div class="input-group-append" data-target="#datetimepicker2" data-toggle="datetimepicker">
                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
                </div>
        </div>
        <div class="col-lg-2 align-self-end">
            <button class="btn btn-primary btn-block text-white" type="submit"><span class="fa fa-search"></span></button>
        </div>
    </div>
</form>
            </div>
        </div>
      </div>
    </section>
{% endblock %}