app/base/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'authentication.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('workers/', include(('workers.urls', 'workers'), namespace='workers')),
    path('hoteladmin/', include(('hoteladmin.urls', 'hoteladmin'), namespace='hoteladmin')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication'))
]

app/base/hoteladmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('empleado/', views.empleado, name='empleado'),
    path('nuevohotel/', views.nuevo_hotel, name='nuevohotel'),
    path('nuevahabitacion/', views.nueva_habitacion, name='nuevahabitacion'),
    path('empleados/', views.buscar_empleado, name='empleados'),
    path('ver_empleado/', views.eliminar_empleado, name='ver_empleado'),
    path('hoteles/', views.buscar_hotel, name='hoteles'),
    path('ver_hotel/', views.eliminar_hotel, name='ver_hotel'),
    path('habitaciones/', views.eliminar_habitacion, name='habitaciones')
]

app/base/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('signup', views.signup, name="signup"),
    path('login', views.login, name="login"),
    path('results', views.hotel_search, name="results"),
    path('rooms', views.available_rooms, name="rooms"),
    path('new_bookings', views.book, name="new_bookings"),
    path('bookings', views.bookings, name="bookings"),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('invoice', views.invoice, name="invoice"),
    path('account', views.info_cuenta, name='account'),
    path('delete_account/<username>/', views.eliminar_cuenta, name='delete'),
]

app/base/hoteladmin/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Disponer(models.Model):
    """
    Modelo que representa disponer
    
    Attributes:
        id_trabajador (ForeignKey): Llave foránea hacia el modelo trabajador.
        id_cuenta (ForeignKey): Llave foránea hacia el modelo cuenta.
        nombre (CharField): Nombre del cliente.
        apellido_materno (CharField): Apellido paterno del cliente.
        apellido_paterno (CharField): Apellido materno del cliente.
        telefono (IntegerField): Telefono del cliente.
        fecha_de_nacimiento (DateField): Fecha de nacimiento del cliente.
        id_hotel (ForeignKey): Llave foránea hacia el modelo hotel.
        correo_electronico (CharField): Correo electronico de la cuenta.
        contrasena (CharField): Contraseña de la cuenta:
        id_cliente (ForeignKey): Llave foránea hacia el modelo hotel.
    """
    id_trabajador = models.IntegerField()
    id_cuenta = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10, unique=True)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)
    id_hotel = models.IntegerField()
    correo_electronico = models.CharField(max_length=100)
    contrasena = models.CharField(max_length=20, validators=[MinLengthValidator(8)])
    id_cliente = models.IntegerField()

    class Meta:
        db_table = 'disponer'
        unique_together = (('id_trabajador', 'id_cuenta'),)
        constraints = [
            models.CheckConstraint(check=models.Q(contrasena__length__gte=8), name='contrasena_trabajador_length_check'),
        ]

    @property
    def nombre_completo(self):
        """
        Regresa el nombre completo del cliente.

        Returns:
            str: Nombre completo.
        """
        return f"{self.nombre} {self.apellido_paterno} {self.apellido_materno}"

    def save(self, *args, **kwargs):
        """
        Guarda los datos.
        """
        super().save(*args, **kwargs)

app/base/hoteladmin/views.py
from django.shortcuts import render, redirect
from authentication.models import Trabajador
from users.models import Hotel
from django.contrib import messages
from django.contrib.auth.models import Group, User, Permission
from django.db.models import Max
from users.models import Hotel, Habitacion
from users.views import get_coordenadas
import os
from django.conf import settings
from django.http import HttpResponse
from django.utils.text import slugify
from PIL import Image
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import permission_required

@permission_required("users.puede_administrar")
def home(request):
    return render(request, 'hoteladmin/adminpanel.html')

@permission_required("users.puede_administrar")
def empleado(request):
    """
    Metodo que guarda un nuevo empleado en la base de datos, solo si el usuario
    que desea administrar el nuevo hotel tiene los permisos necesarios.
    
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == "POST":
        username = request.POST['username']
        nombre = request.POST['nombre']
        apellido_paterno = request.POST['apellido_paterno']
        apellido_materno= request.POST['apellido_materno']
        telefono = request.POST['telefono']
        fecha_de_nacimiento = request.POST['fecha_de_nacimiento']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "El usuario ya existe. Intente con otro distinto")
            return redirect('hoteladmin:empleado')

        if User.objects.filter(email=email).exists():
            messages.error(request, "Ya existe una cuenta con ese correo electrónico")
            return redirect('hoteladmin:empleado')

        if Trabajador.objects.filter(telefono=telefono).exists():
            messages.error(request, "Ya existe una cuenta con ese teléfono")
            return redirect('hoteladmin:empleado')

        if len(username) > 15:
            messages.error(request, "El usuario excedió el límite de carácteres")
            return redirect('hoteladmin:empleado')

        if pass1!=pass2:
            messages.error(request, "Las contraseñas no coinciden")
            return redirect('hoteladmin:empleado')

        if not username.isalnum():
            messages.error(request, "Usuario con carácteres inválidos.")
            return redirect('hoteladmin:empleado')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name= nombre
        myuser.last_name= apellido_paterno
        myuser.save()
        worker_group = Group.objects.get(name="Trabajador")
        myuser.groups.add(worker_group)

        myuser_db = Trabajador(
            id_trabajador = myuser.id,
            nombre = nombre,
            apellido_materno = apellido_materno,
            apellido_paterno = apellido_paterno,
            telefono = telefono, 
            fecha_de_nacimiento = fecha_de_nacimiento
        )
        myuser_db.save()


        registro_cuenta = User.objects.filter(username=username).exists()

        if registro_cuenta:
            messages.success(request, "¡Cuenta creada con éxito!")
        else:
            messages.error(request, "Error al crear cuenta. Vuelva a intentar")

        return redirect('hoteladmin:home')
    
    return render(request, 'hoteladmin/signup.html')

@permission_required("users.puede_administrar")
def nuevo_hotel(request):
    """
    Metodo que guarda un nuevo hotel en la base de datos, solo si el usuario
    que desea administrar el nuevo hotel tiene los permisos necesarios.
    
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == "POST":
        nombre = request.POST['nombre']
        numero = request.POST['numero']
        calle = request.POST['calle']
        estado = request.POST['estado']
        colonia = request.POST['colonia']
        pais = request.POST['pais']
        image = request.FILES.get('image')

        if not image:
            return HttpResponse("No se subió ninguna imagen", status=400)

        if Hotel.objects.filter(nombre=nombre):
            messages.error(request, "Un hotel con ese nombre ya está dado de alta")
            return redirect('hoteladmin:nuevohotel')
        
        try:
            numero = int(numero)
        except ValueError:
            messages.error(request, "El valor ingresado en número no es un entero")
            return redirect('hoteladmin:nuevohotel')
        
        if numero <= 0:
            messages.error(request, "El número ingresado no es válido")
            return redirect('hoteladmin:nuevohotel')
        
        try:
            img = Image.open(image)
            if img.format != 'JPEG':
                return HttpResponse("La imagen no es JPG", status=400)
        except Exception as e:
            return HttpResponse("Archivo no válido", status=400)
        
        direccion = calle + ', ' + str(numero) + ', ' + colonia + ', ' + estado + ', ' + pais
 
        (latitud, longitud) = get_coordenadas(direccion)

        max_hotel = Hotel.objects.aggregate(max_value = Max('id_hotel'))['max_value']
        if max_hotel is None:
            max_hotel = 0

        hotel = Hotel(
            id_hotel = max_hotel + 1,
            numero = numero,
            nombre = nombre,
            calle = calle,
            estado = estado,
            colonia = colonia,
            pais = pais,
            latitud = latitud,
            longitud = longitud
        )
        hotel.save()

        custom_filename = slugify(str(hotel.id_hotel))
        new_filename = f'{custom_filename}.jpg'
        save_path = os.path.join(settings.MEDIA_ROOT, new_filename)
        os.makedirs(os.path.dirname(save_path), exist_ok=True) # Verificar que el directorio existe
        # Escribir el archivo en la ruta especificada
        with open(save_path, 'wb+') as destination:
            for chunk in image.chunks():
                destination.write(chunk)

        registro_hotel = Hotel.objects.filter(nombre=nombre).exists()

        if registro_hotel:
            messages.success(request, "¡Hotel creado con éxito!")
        else:
            messages.error(request, "Error al crear hotel. Vuelva a intentar")

        return redirect('hoteladmin:home')

    return render(request, 'hoteladmin/newhotel.html')


@permission_required("users.puede_administrar")
def nueva_habitacion(request):
    """
    Metodo que guarda una nueva habitacion de un hotel en la base de datos, solo si el usuario
    que desea administrar el nuevo hotel tiene los permisos necesarios.
    
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == "POST":
        id_hotel = request.POST['hotel']
        numero = request.POST['numero']
        esta_disponible = request.POST['disponibilidad']
        costo = request.POST['costo']
        tipo = request.POST['tipo']
        
        try:
            numero = int(numero)
        except ValueError:
            messages.error(request, "El valor ingresado en número no es un entero")
            return redirect('hoteladmin:home')
        
        if numero <= 0:
            messages.error(request, "El número ingresado no es válido")
            return redirect('hoteladmin:home')
        
        try:
            costo = float(costo)
        except ValueError:
            messages.error(request, "El valor ingresado en costo no es válido")
            return redirect('hoteladmin:home')
        
        if costo <= 0:
            messages.error(request, "El costo no puede ser negativo")
            return redirect('hoteladmin:home')

        habitaciones_hotel = Habitacion.objects.filter(id_hotel = id_hotel)
        max_habitacion = habitaciones_hotel.aggregate(max_value = Max('id_habitacion'))['max_value']
        if max_habitacion is None:
            max_habitacion = 0

        hotel = Hotel.objects.get(id_hotel=id_hotel)

        habitacion = Habitacion(
            id_habitacion = max_habitacion + 1,
            id_hotel = hotel,
            numero = numero,
            esta_disponible = esta_disponible,
            costo = costo,
            tipo = tipo
        )
        habitacion.save()

        id_habitacion = habitacion.id_habitacion

        registro_habitacion = Habitacion.objects.filter(id_habitacion=id_habitacion).exists()

        if registro_habitacion:
            messages.success(request, "¡Habitación creada con éxito!")
        else:
            messages.error(request, "Error al crear habitación. Vuelva a intentar")

        return redirect('hoteladmin:home')

    else:
        hoteles = Hotel.objects.all().order_by('nombre')
        return render(request, 'hoteladmin/newroom.html', {'hoteles': hoteles})
    

@permission_required("users.puede_administrar")
def buscar_empleado(request):
    """
    Busca a un empleado dentro de la base de datos, solo si el usuario que desea 
    realizar la busqueda tiene los permisos necesarios para invocar la funcion.

    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == 'POST': 
        telefono = request.POST['telefono']

        try:
            trabajador = Trabajador.objects.get(telefono = telefono)
        except ObjectDoesNotExist:

app/base/hoteladmin/templates/hoteladmin/adminpanel.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}

<style>
    body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }
    .admin-panel {
        background-color: white;
        border: 2px solid #ddd;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 30px; /* Increased padding for larger panel */
        width: 400px; /* Increased width for larger panel */
    }
    .admin-panel h1 {
        font-size: 32px; /* Increased font size for header */
        margin-bottom: 30px; /* Increased margin for better spacing */
        text-align: center;
    }
    .admin-list {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }
    .admin-list li {
        margin: 15px 0; /* Increased margin for larger spacing between items */
    }
    .admin-list a {
        text-decoration: none;
        color: #007bff;
        font-size: 20px; /* Increased font size for links */
        padding: 15px 20px; /* Increased padding for larger clickable area */
        display: block;
        background-color: #f4f4f4;
        border-radius: 4px;
    }
    .admin-list a:hover {
        background-color: #e9ecef;
    }
    .return-link {
        color: #28a745;
    }
    .return-link:hover {
        background-color: #d4edda;
    }
</style>

<nav role="navigation">
    <div class="admin-panel">
        <h1>Panel de administración</h1>
        <ul class="admin-list">
            <li><a href="{% url 'hoteladmin:empleado' %}">Alta de empleados</a></li>
            <li><a href="{% url 'hoteladmin:empleados' %}">Administrar empleados</a></li>
            <li><a href="{% url 'hoteladmin:nuevohotel' %}">Alta de hotel</a></li>
            <li><a href="{% url 'hoteladmin:hoteles' %}">Administrar hoteles</a></li>
            <li><a href="{% url 'hoteladmin:nuevahabitacion' %}">Alta de habitación</a></li>
            <li><a href="{% url 'hoteladmin:habitaciones' %}">Administrar habitaciones</a></li>
            <li><a class="return-link" href="{% url 'users:homepage' %}">Página principal</a></li>
        </ul>
    </div>
</nav>

{% endblock %}

app/base/hoteladmin/templates/hoteladmin/delete_employee.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}   

<style>
    body {
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: #f0f0f0;
    }
    .container {
        max-width: 600px;
        background: #f9f9f9;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
        color: #333;
        text-align: center;
    }
    .details {
        margin-top: 20px;
    }
    .details p {
        margin-bottom: 10px;
        font-size: 16px;
    }
    .details strong {
        font-weight: bold;
    }
    .delete-button {
            display: block;
            width: 100%;
            text-align: center;
            margin-top: 20px;
        }
    .delete-button button {
        padding: 10px 20px;
        background-color: #dc3545;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    .delete-button button:hover {
        background-color: #c82333;
    }
    .back-link {
        display: block;
        text-align: center;
        margin-top: 20px;
        text-decoration: none;
        color: #007bff;
    }
    .back-link:hover {
        text-decoration: underline;
    }
</style>

<body>
    <div class="container">
        <h1>Información del trabajador</h1>
        <div class="details">
            <p><strong>Nombre:</strong> {{ trabajador.nombre_completo }}</p>
            <p><strong>Apellido Paterno:</strong> {{ trabajador.apellido_paterno }}</p>
            <p><strong>Apellido Materno:</strong> {{ trabajador.apellido_materno }}</p>
            <p><strong>Telefono:</strong> {{ trabajador.telefono }}</p>
            <p><strong>Fecha de Nacimiento:</strong> {{ trabajador.fecha_de_nacimiento }}</p>
            <p><strong>ID Trabajador:</strong> {{ trabajador.id_trabajador }}</p>
            <p><strong>ID Hotel:</strong> {{ trabajador.id_hotel }}</p>
        </div>
        <div class="delete-button">
            <form action="{% url 'hoteladmin:ver_empleado' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="trabajador_id" value="{{ trabajador.id_trabajador }}">
                <button type="submit">Borrar Trabajador</button>
            </form>
        </div>
        <a class="back-link" href="{% url 'hoteladmin:home' %}">Regresar al panel de administracion</a>
    </div>
</body>

{% endblock %}

app/base/hoteladmin/templates/hoteladmin/delete_hotel.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}   

<section class="site-hero overlay" style="background-image: url({% static 'images/signupPage.jpg' %})" data-stellar-background-ratio="0.5">

<div class="container">
    <div class="row site-hero-inner justify-content-center align-items-center">
        <div class="col-md-10 text-center" data-aos="fade-up">

            <main class="container mt-5">
                <div class="row justify-content-center">
                    <section class="col-md-12">
                        <form action="{% url 'hoteladmin:ver_hotel' %}" method="POST" class="card card-body" enctype="multipart/form-data">
                            <h3 class="text-center">Eliminar un hotel</h3>
                            {% csrf_token %} 

                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label for="nombre">Nombre:</label>
                                    <p>{{ hotel.nombre }}</p>
                                </div>
                                <div class="col-md-4">
                                    <label for="numero">Número:</label>
                                    <p>{{ hotel.numero }}</p>
                                </div>
                                <div class="col-md-4">
                                    <label for="calle">Calle:</label>
                                    <p>{{ hotel.calle }}</p>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label for="colonia">Colonia:</label>
                                    <p>{{ hotel.colonia }}</p>
                                </div>
                                <div class="col-md-4 mt-3">
                                    <label for="estado">Estado:</label>
                                    <p>{{ hotel.estado }}</p>
                                </div>
                                <div class="col-md-4 mt-3">
                                    <label for="pais">País:</label>
                                    <p>{{ hotel.pais }}</p>
                                </div>

                                <div class="col-md-4 mt-3">
                                    <label for="image">ID del hotel:</label>
                                    <p>{{ hotel.id_hotel }}</p>
                                </div>
                                <div class="col-md-4 mt-3">
                                    <label for="">Dar de baja el hotel</label>
                                        <input type="hidden" name="hotel_id" value="{{ hotel.id_hotel }}">
                                        <button type="submit" class="btn btn-primary btn-block">Eliminar &nbsp; <i class="fa fa-user" aria-hidden="true"></i></button>
                                </div>
                            </div>
                        </form>
                    </section>
                </div>
            </main>
        </div>
    </div>
</div>


{% endblock %}

app/base/hoteladmin/templates/hoteladmin/delete_rooms.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}   

<section class="site-hero overlay" style="background-image: url({% static 'images/signupPage.jpg' %})" data-stellar-background-ratio="0.5">

    <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade-up">
    
                <main class="container mt-5">
                    <div class="row justify-content-center">
                        <section class="col-md-12">
                            <form action="{% url 'hoteladmin:habitaciones' %}" method="POST" class="card card-body">
                                <h3 class="text-center">Eliminar una habitación</h3>
                                {% csrf_token %} 
    
                                    <div>
                                        <label for="hotel">Hotel:</label>
                                        <select id="hotel" name="hotel">
                                            {% for hotel in hoteles %}
                                                <option value="{{ hotel.id_hotel }}">{{ hotel.nombre }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div>
                                        <label for="numero">Número:</label>
                                        <input type="text" id="numero" name="numero" required>
                                    </div>
                                    <div>
                                        <label for="">Dar de baja la habitación</label>
                                        <button type="submit" class="btn btn-primary btn-block">Eliminar &nbsp; <i class="fa fa-user" aria-hidden="true"></i></button>
                                    </div>
                                </div>
                            </form>
    
                        </section>
                    </div>
                </main>
            </div>
        </div>
    </div>
    
    
    {% endblock %}

app/base/hoteladmin/templates/hoteladmin/employee.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

{% csrf_token %}

    <section class="site-hero inner-page overlay" style="background-image: url({% static 'images/invoicePage.png' %})" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade">
                <h2 class="text-white d-block  mb-3">Busca a cualquier</h2>
                <h1 class="heading">empleado</h1>
            </div>
        </div>
      </div>


<section class="section contact-section">
      <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-md-7" data-aos="fade-up" data-aos-delay="100">
              <form method="post" class="bg-white p-md-5 p-4 mb-5 border" >
            {% csrf_token %}
            

            <div class="row">
                <div class="col-md-12 form-group">
                  <label class="text-black font-weight-bold" for="telefono">Teléfono del trabajador</label>
                  <input type="text" name="telefono" class="form-control ">
                </div>
              </div>
                
                <hr/>
              <div class="row">
                <div class="col-md-6 form-group">
                    <button type="submit" class="btn btn-primary text-white font-weight-bold">Buscar empleado</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

app/base/hoteladmin/templates/hoteladmin/hotels.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

{% csrf_token %}

<section class="site-hero inner-page overlay" style="background-image: url({% static 'images/invoicePage.png' %})" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade">
                <h2 class="text-white d-block  mb-3">Buscascador de</h2>
                <h1 class="heading">hoteles</h1>
            </div>
        </div>
    </div>
</section>


<section class="section contact-section">
      <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-md-7" data-aos="fade-up" data-aos-delay="100">
              <form method="post" class="bg-white p-md-5 p-4 mb-5 border" >
            {% csrf_token %}
            

            <div class="row">
                <div class="col-md-12 form-group">
                    <label for="hotel">Hotel:</label>
                    <select id="hotel" name="hotel">
                        {% for hotel in hoteles %}
                            <option value="{{ hotel.id_hotel }}">{{ hotel.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
              </div>
                
                <hr/>
              <div class="row">
                <div class="col-md-6 form-group">
                    <button type="submit" class="btn btn-primary text-white font-weight-bold">Ver hotel</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

app/base/hoteladmin/templates/hoteladmin/newroom.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}   

<section class="site-hero overlay" style="background-image: url({% static 'images/signupPage.jpg' %})" data-stellar-background-ratio="0.5">

    <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade-up">
    
                <main class="container mt-5">
                    <div class="row justify-content-center">
                        <section class="col-md-12">
                            <form action="{% url 'hoteladmin:nuevahabitacion' %}" method="POST" class="card card-body">
                                <h3 class="text-center">Registrar una nueva habitación</h3>
                                {% csrf_token %} 
    
                                    <div>
                                        <label for="hotel">Hotel:</label>
                                        <select id="hotel" name="hotel">
                                            {% for hotel in hoteles %}
                                                <option value="{{ hotel.id_hotel }}">{{ hotel.nombre }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div>
                                        <label for="numero">Numero:</label>
                                        <input type="text" id="numero" name="numero" required>
                                    </div>
                                    <div>
                                        <label for="disponibilidad">Está Disponible:</label>
                                        <select id="disponibilidad" name="disponibilidad">
                                            <option value="True">Sí</option>
                                            <option value="False">No</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label for="costo">Costo:</label>
                                        <input type="text" id="costo" name="costo" required>
                                    </div>
                                    <div>
                                        <label for="tipo">Tipo:</label>
                                        <select id="tipo" name="tipo">
                                            <option value="Individual">Individual</option>
                                            <option value="Doble">Doble</option>
                                            <option value="Triple">Triple</option>
                                            <option value="Cuadruple">Cuadruple</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label for="">Dar de alta la habitación</label>
                                        <button type="submit" class="btn btn-primary btn-block">Registrar &nbsp; <i class="fa fa-user" aria-hidden="true"></i></button>
                                    </div>
                                </div>
                            </form>
    
                        </section>
                    </div>
                </main>
            </div>
        </div>
    </div>
    
    
    {% endblock %}