app/base/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'authentication.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),
    path('workers/', include(('workers.urls', 'workers'), namespace='workers')),
    path('hoteladmin/', include(('hoteladmin.urls', 'hoteladmin'), namespace='hoteladmin')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication'))
]

app/base/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('signup', views.signup, name="signup"),
    path('login', views.login, name="login"),
    path('results', views.hotel_search, name="results"),
    path('rooms', views.available_rooms, name="rooms"),
    path('new_bookings', views.book, name="new_bookings"),
    path('bookings', views.bookings, name="bookings"),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('invoice', views.invoice, name="invoice"),
    path('account', views.info_cuenta, name='account'),
    path('delete_account/<username>/', views.eliminar_cuenta, name='delete'),
]

app/base/workers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.generador, name='workers'),
    path('vencimiento', views.vencimiento, name='vencimiento'),
    path('new_invoice', views.generar_factura, name='new_invoice')
]

app/base/workers/models.py
from django.db import models
from users.models import Reservacion

class Factura(models.Model):
    """
    Modelo que representa la cuenta de gastos de un cliente por una reservación.

    Attributes:
        id_factura (AutoField): Llave primaria.
        vencimiento (DateField): Fecha de vencimiento.
        emision (DateField): Fecha de emisión.
        total (FloatField): Costo total de la cuenta.
    """
    id_factura = models.AutoField(primary_key=True)
    vencimiento = models.DateField()
    emision = models.DateField()
    total = models.FloatField()

    class Meta:
        db_table = 'factura'

class Generar(models.Model):
    """
    Modelo que representa la relación entre una reservación y una cuenta de gastos.

    Attributes:
        id_generar (IntegerField): Llave primaria.
        id_reservacion (ForeignKey): Llave foránea hacia el modelo reservación.
        id_factura (ForeignKey): Llave foránea hacia el modelo factura.
    """
    id_generar = models.IntegerField(primary_key=True)
    id_reservacion = models.ForeignKey(Reservacion, on_delete=models.CASCADE, db_column='id_reservacion')
    id_factura = models.ForeignKey(Factura, on_delete=models.CASCADE, db_column='id_factura')

    class Meta:
        db_table = 'generar'
        unique_together = (('id_reservacion', 'id_factura'),)

app/base/workers/views.py
from django.shortcuts import render, redirect
from authentication.models import Cliente, Cuenta
from users.models import Reservacion
from django.db.models import F, ExpressionWrapper, fields, IntegerField, FloatField
from django.db.models.functions import ExtractDay
from django.db.models import Sum
import datetime
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from workers.models import Factura, Generar
from users.models import Reservacion
from django.contrib.auth.decorators import permission_required

@permission_required("workers.puede_generar")
def generador(request):
    """
    Página para generar cuentas de gastos.
    Dado un correo electrónico, redirige a una página
    con las reservaciones del cliente propietario de ese correo.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == 'POST': 
        data = request.POST
        return view_bookings(request, data)

    return render(request, 'workers/generador.html')

@permission_required("workers.puede_generar")
def view_bookings(request, data):
    """
    Muestra a un empleado todas las reservaciones de un cliente, 
    de modo que pueda elegir a cual reservación generar una cuenta y a cual no.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    email = data.get('email')

    try:
        id_cliente = Cuenta.objects.get(correo_electronico = email).id_cliente
    except ObjectDoesNotExist:
        messages.error(request, "No existe ninguna cuenta con ese correo")
        return redirect('/workers')
    
    try:
        reservaciones = Reservacion.objects.filter(id_cliente = id_cliente)
        reservaciones_to_exclude = Generar.objects.filter(id_reservacion__in=reservaciones).values('id_reservacion')
        filtered_reservaciones = reservaciones.exclude(id_reservacion__in=reservaciones_to_exclude)
    except Exception:
        messages.error(request, "El cliente no tiene reservaciones o ya están facturadas")
        return redirect('/workers')
    
    context = {
        'reservaciones': filtered_reservaciones,
        'correo': email
    }
        
    return render(request, 'workers/client_bookings.html', context)

@permission_required("workers.puede_generar")
def vencimiento(request):
    """
    Dada una reservación, esta página permite a un empleado
    seleccionar una fecha de vencimiento para la cuenta de gastos.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == 'POST': 
        reservacion_id = request.POST.get('reservacion_id')
        correo = request.POST.get('correo')

        context = {
            'reservacion': reservacion_id,
            'correo': correo
        }

        return render(request, 'workers/vencimiento.html', context)

    return render(request, 'workers/generador.html')

@permission_required("workers.puede_generar")
def generar_factura(request):
    """
    Permite generar una cuenta de gastos a partir de la reservación de un cliente 
    y una fecha de vencimiento, si se genera correctamente entonces 
    redirige al empleado hacia ella para que pueda verla, 
    con datos como las noches pasadas y el costo total.
        
    Args:
        request (HttpRequest): El objeto HttpRequest que contiene metadatos sobre la solicitud.
    Returns:
        HttpResponse: La plantilla respectiva representada como un objeto HttpResponse.
    """
    if request.method == 'POST':
        id_reservacion = request.POST.get('reservacion')
        email = request.POST.get('correo')
        vencimiento = request.POST.get('fecha')

        emision = datetime.datetime.now().strftime("%Y-%m-%d")

        if vencimiento < emision:
            messages.error(request, "Por favor ingrese una fecha igual o posterior a la actual")
            return redirect('/workers')

        try:
            id_cliente = Cuenta.objects.get(correo_electronico = email).id_cliente
        except ObjectDoesNotExist:
            messages.error(request, "No existe ninguna cuenta con ese correo")
            return redirect('/workers')
        
        cliente = Cliente.objects.get(id_cliente = id_cliente)
        
        reservacion = Reservacion.objects.filter(id_reservacion=id_reservacion).annotate(
            noches = ExtractDay(F('check_out') - F('check_in'))
        ).annotate(
            subtotal = F('id_habitacion__costo') * F('noches')
        )
        
        if not reservacion.exists():
            messages.error(request, "Reservación no encontrada")
            return redirect('/workers')

        total = reservacion.aggregate(
            total=Sum(F('subtotal'))
        )['total'] 

        factura = Factura(
            vencimiento = vencimiento,
            emision = emision,
            total = total
        )
        factura.save()

        reservacion_actual = Reservacion.objects.get(id_reservacion = id_reservacion)

        registro_factura = Generar(
            id_reservacion = reservacion_actual,
            id_factura = factura
        )
        registro_factura.save()
        
        context = {
            'cliente': cliente, 
            'reservaciones': reservacion, 
            'total': total, 
            'email': email,
            'emision': emision,
            'vencimiento': vencimiento,
            'esCliente': False 
        }
        return render(request, 'workers/factura.html', context)

    else:
        return render(request, 'index.html')

app/base/workers/templates/workers/client_bookings.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

<style>
    table {
        text-align: center;
    }
</style>

    <section class="site-hero inner-page overlay" style="background-image: url({% static 'images/bookingPage.png' %})" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade">
                <h2 class="text-white d-block  mb-3">Reservaciones del cliente</h2>
            </div>
        </div>
      </div>

<div class="container">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Hotel</th>
                        <th>Destino</th>
                        <th>Costo</th>
                        <th>Check-in</th>
                        <th>Check-out</th>
                        <th>Cuenta de gastos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for reservacion in reservaciones %}
                    <form action="{% url 'workers:vencimiento' %}" method="POST">
                        {% csrf_token %}
                        <tr>
                            <input type="hidden" name="reservacion_id" value="{{ reservacion.id_reservacion }}">
                            <input type="hidden" name="correo" value="{{ correo }}">
                            <td class="align-middle">{{ reservacion.id_hotel.nombre }}</td>
                            <td class="align-middle">{{ reservacion.id_hotel.estado }}</td>
                            <td class="align-middle">${{ reservacion.costo }}</td>
                            <td class="align-middle">{{ reservacion.check_in }}</td>
                            <td class="align-middle">{{ reservacion.check_out }}</td>
                            <td class="align-middle"> 
                                <button class="btn btn-primary text-white py-2" type="submit">
                                    <span class="text-uppercase letter-spacing-1">Generar</span>
                                </button>
                            </td>
                        </tr>
                    </form>
                    {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">El cliente aún no tiene reservaciones.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

app/base/workers/templates/workers/factura.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">

{% load static %}

<title>Hoteles Estrella</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'css/bootstrap5.min.css' %}" rel="stylesheet">
<link href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}" rel="stylesheet">
<style type="text/css">
    	body{margin-top:20px;
background-color:#eee;
}

.card {
    box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: 1rem;
}
    </style>
</head>
<body>
<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-body">
<div class="invoice-title">
<h4 class="float-end font-size-15"> </h4>
<div class="mb-4">
<h2 class="mb-1 text-muted">Hoteles Estrella</h2>
</div>
</div>
<hr class="my-4">
<div class="row">
<div class="col-sm-6">
<div class="text-muted">
<h5 class="font-size-16 mb-3">Cuenta para:</h5>
<h5 class="font-size-15 mb-2">{{cliente.nombre_completo}}</h5>
<p class="mb-1">{{email}}</p>
<p class="mb-1">{{cliente.telefono}}</p>
</div>
</div>


<div class="col-sm-6">
<div class="text-muted text-sm-end">
<div>
<h5 class="font-size-15 mb-1">Fecha de emisión:</h5>
<p>{{emision}}</p>
</div>
<div class="mt-4">
<h5 class="font-size-15 mb-1">Fecha de vencimiento:</h5>
<p>{{vencimiento}}</p>
</div>
</div>
</div>





</div>

<div class="py-2">
<div class="table-responsive">
<table class="table align-middle table-nowrap table-centered mb-0">
<thead>


<tr>
<th>Hotel</th>
<th>Precio por noche</th>
<th>Noches</th>
<th class="text-end" style="width: 120px;">Subtotal</th>
</tr>
</thead>
<tbody>

{% for reserva in reservaciones %}
<tr>
<td>
<div>
<h5 class="text-truncate font-size-14 mb-1">{{reserva.id_hotel.nombre}}</h5>
<p class="text-muted mb-0">{{reserva.id_hotel.calle}} {% if reserva.id_hotel.numero == None %} s/n, {% else %} {{ reserva.id_hotel.numero }}, {% endif %} {{reserva.id_hotel.colonia}}, {{reserva.id_hotel.estado}}.</p>
</div>
</td>
<td>$ {{reserva.id_habitacion.costo}}</td>
<td>{{reserva.noches}}</td>
<td class="text-end">$ {{reserva.subtotal|floatformat:"-3"}}</td>
</tr>
{% endfor %}

<tr>
<td colspan="3" class="border-0 text-end"><strong>Total</strong></td>
<td class="border-0 text-end"><h4 class="m-0 fw-semibold">${{total|floatformat:"-3"}}</h4></td>
</tr>
</tbody>
</table>

</div>
<div class="d-print-none mt-4">
<div class="float-end ms-2">
<a href="javascript:window.print()" class="btn btn-success me-1"><i class="fa fa-print"></i></a>
</div>
</div>

<div class="float-end">
{% if esCliente %}
    <a href="{% url 'users:bookings' %}" class="btn btn-primary">Regresar</a> 
{% else %}
    <a href="{% url 'workers:workers' %}" class="btn btn-primary">Generar otra cuenta</a> 
{% endif %}
</div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>

app/base/workers/templates/workers/generador.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

{% csrf_token %}

    <section class="site-hero inner-page overlay" style="background-image: url({% static 'images/invoicePage.png' %})" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade">
                <h2 class="text-white d-block  mb-3">Con el correo del cliente genera una</h2>
                <h1 class="heading">cuenta de los gastos</h1>
            </div>
        </div>
      </div>


<section class="section contact-section">
      <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-md-7" data-aos="fade-up" data-aos-delay="100">
              <form method="post" class="bg-white p-md-5 p-4 mb-5 border" >
            {% csrf_token %}
            

            <div class="row">
                <div class="col-md-12 form-group">
                  <label class="text-black font-weight-bold" for="email">Correo electrónico</label>
                  <input type="text" name="email" class="form-control ">
                </div>
              </div>
                
                <hr/>
              <div class="row">
                <div class="col-md-6 form-group">
                    <button type="submit" class="btn btn-primary text-white font-weight-bold">Buscar reservaciones</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

app/base/workers/templates/workers/vencimiento.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}      

{% csrf_token %}

    <section class="site-hero inner-page overlay" style="background-image: url({% static 'images/invoicePage.png' %})" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
            <div class="col-md-10 text-center" data-aos="fade">
                <h2 class="text-white d-block  mb-3">Generar cuenta de gastos</h2>
            </div>
        </div>
      </div>


<section class="section contact-section">
      <div class="container">
        <div class="row justify-content-center align-items-center">
          <div class="col-md-7" data-aos="fade-up" data-aos-delay="100">
            <form action="{% url 'workers:new_invoice' %}" method="POST" class="bg-white p-md-5 p-4 mb-5 border">
            {% csrf_token %}
                
             <div class="row">
                <div class="col-md-12 form-group">
                  <label class="text-black font-weight-bold" for="fecha">Fecha de vencimiento</label>
                  <input type="date" name="fecha" class="form-control ">
                  <input type="hidden" name="reservacion" value="{{ reservacion }}">
                  <input type="hidden" name="correo" value="{{ correo }}">
                </div>
              </div>
                
                <hr/>
              <div class="row">
                <div class="col-md-6 form-group">
                    <button type="submit" class="btn btn-primary text-white font-weight-bold">Generar cuenta</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

{% endblock %}